{ config, pkgs, inputs,... }:

{
  imports = [./hardware-configuration.nix ]; # Automatically generated by nixos-generate-config

  networking.hostName = "dt-sora";

  # Intel Microcode for 13600K
  hardware.cpu.intel.updateMicrocode = true;

  # Nvidia Configuration for RTX 4090
  services.xserver.videoDrivers = [ "nvidia" ];
  hardware.opengl = {
    enable = true;
    driSupport = true;
    driSupport32Bit = true;
  };
  hardware.nvidia = {
    modesetting.enable = true;
    powerManagement.enable = false;
    open = false; # Use proprietary drivers for full performance
    nvidiaSettings = true;
    # Ensures driver 555+ for Wayland explicit sync
    package = config.boot.kernelPackages.nvidiaPackages.beta; 
  };

  # Wayland Environment Variables
  environment.sessionVariables = {
    NIXOS_OZONE_WL = "1"; # Forces Electron apps to use Wayland [4]
    ELECTRON_OZONE_PLATFORM_HINT = "auto"; [3]
  };

  # High-Fidelity Gaming
  programs.gamemode.enable = true;
  programs.steam = {
    enable = true;
    gamescopeSession.enable = true;
    extraCompatPackages = with pkgs; [ proton-ge-bin ];
  };
  
  environment.systemPackages = with pkgs;
    mangohud
  ];

  # Allow unfree packages (required for Nvidia and Steam)
  nixpkgs.config.allowUnfree = true;

  # Enable Flakes
  nix.settings.experimental-features = [ "nix-command" "flakes" ];

  system.stateVersion = "24.05";
}